version: '3'
services:
  jenkins-docker:
    image: docker:dind
    privileged: true
    ports:
      - 2376:2376
    environment:
      DOCKER_TLS_CERTDIR: /certs
    networks:
      jenkins:
        aliases:
          - docker
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    command: --storage-driver=overlay2
  jenkins:
    build: .
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    depends_on:
      - jenkins-docker
    networks:
      - jenkins
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
volumes:
  jenkins-docker-certs:
  jenkins-data:
networks:
  jenkins:
